/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KhetSeRasoiTakRouteImport } from './routes/khet-se-rasoi-tak'
import { Route as HygieneRouteImport } from './routes/hygiene'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryAreasRouteImport } from './routes/delivery-areas'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminZonesRouteImport } from './routes/_authenticated/admin/zones'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KhetSeRasoiTakRoute = KhetSeRasoiTakRouteImport.update({
  id: '/khet-se-rasoi-tak',
  path: '/khet-se-rasoi-tak',
  getParentRoute: () => rootRouteImport,
} as any)
const HygieneRoute = HygieneRouteImport.update({
  id: '/hygiene',
  path: '/hygiene',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryAreasRoute = DeliveryAreasRouteImport.update({
  id: '/delivery-areas',
  path: '/delivery-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminZonesRoute = AuthenticatedAdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/delivery-areas': typeof DeliveryAreasRoute
  '/faq': typeof FaqRoute
  '/hygiene': typeof HygieneRoute
  '/khet-se-rasoi-tak': typeof KhetSeRasoiTakRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/delivery-areas': typeof DeliveryAreasRoute
  '/faq': typeof FaqRoute
  '/hygiene': typeof HygieneRoute
  '/khet-se-rasoi-tak': typeof KhetSeRasoiTakRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/delivery-areas': typeof DeliveryAreasRoute
  '/faq': typeof FaqRoute
  '/hygiene': typeof HygieneRoute
  '/khet-se-rasoi-tak': typeof KhetSeRasoiTakRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cancellation-policy'
    | '/contact'
    | '/corporate'
    | '/delivery-areas'
    | '/faq'
    | '/hygiene'
    | '/khet-se-rasoi-tak'
    | '/menu'
    | '/order'
    | '/plans'
    | '/privacy'
    | '/subscription'
    | '/terms'
    | '/admin'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/zones'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cancellation-policy'
    | '/contact'
    | '/corporate'
    | '/delivery-areas'
    | '/faq'
    | '/hygiene'
    | '/khet-se-rasoi-tak'
    | '/menu'
    | '/order'
    | '/plans'
    | '/privacy'
    | '/subscription'
    | '/terms'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/zones'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cancellation-policy'
    | '/contact'
    | '/corporate'
    | '/delivery-areas'
    | '/faq'
    | '/hygiene'
    | '/khet-se-rasoi-tak'
    | '/menu'
    | '/order'
    | '/plans'
    | '/privacy'
    | '/subscription'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/zones'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DeliveryAreasRoute: typeof DeliveryAreasRoute
  FaqRoute: typeof FaqRoute
  HygieneRoute: typeof HygieneRoute
  KhetSeRasoiTakRoute: typeof KhetSeRasoiTakRoute
  MenuRoute: typeof MenuRoute
  OrderRoute: typeof OrderRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khet-se-rasoi-tak': {
      id: '/khet-se-rasoi-tak'
      path: '/khet-se-rasoi-tak'
      fullPath: '/khet-se-rasoi-tak'
      preLoaderRoute: typeof KhetSeRasoiTakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hygiene': {
      id: '/hygiene'
      path: '/hygiene'
      fullPath: '/hygiene'
      preLoaderRoute: typeof HygieneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-areas': {
      id: '/delivery-areas'
      path: '/delivery-areas'
      fullPath: '/delivery-areas'
      preLoaderRoute: typeof DeliveryAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/zones': {
      id: '/_authenticated/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminZonesRoute: typeof AuthenticatedAdminZonesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminZonesRoute: AuthenticatedAdminZonesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DeliveryAreasRoute: DeliveryAreasRoute,
  FaqRoute: FaqRoute,
  HygieneRoute: HygieneRoute,
  KhetSeRasoiTakRoute: KhetSeRasoiTakRoute,
  MenuRoute: MenuRoute,
  OrderRoute: OrderRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
